### ISSUE TITLE
JSON5: invalid character '$'

### ISSUE THREAD

**Issue by shwanton** [ConduitVC/aws-utils#111]
Attempting to `#set` a variable that is used in a request template. 

This request template works when pushed to AppSync, just not when invoked from `serverless-appsync-offline`

```
#set( $limit = $util.defaultIfNull($context.args.limit, 10) )
{
  "version": "2017-02-28",
  "operation": "Scan",
  "limit": $limit
}
```

I'm getting this error when the `$context.args.limit` is `null`
```
{
  "errors": [
    {
      "message": "JSON5: invalid character '$' at 4:12",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "listOrganizations"
      ]
    }
  ],
  "data": {
    "listOrganizations": null
  }
}
```

Looks like `$limit` is not being interpolated correctly?
I've tried this with other `$context.args` fields and get similar errors.

If I call `$util.toJson($context.args)` I can see the args, but when I assign them to a variable it throws.

**Comment by shwanton** [comment]
After looking at a request in the [example repo](https://github.com/ConduitVC/appsync-serverless-emulator-example/blob/master/mapping-templates/scan-request.txt), it looks like this will work:
```
{
  "version": "2017-02-28",
  "operation": "Scan",
  "limit": #if($context.arguments.limit) "$context.arguments.limit" #else 10 #end,
}
```
Is `$util.defaultIfNull` available inside of the emulator?

I'm also not getting a value back for `$util.transform.toDynamoDBFilterExpression` and would have to build out the filter expression manually.

I created these original request templates using the [AmplifyCLI](https://aws-amplify.github.io/docs/js/api). I was hoping to test them first in offline mode.

**Comment by cbaron** [comment]
Hi @shwanton -- thanks for flagging this issue.  Glad to know another user of the emulator!

Regarding `defaultIfNull`, its available [here](https://github.com/ConduitVC/aws-utils/blob/3cb3521acbc642a429f8a5157982c9906752a434/packages/appsync-emulator-serverless/util.js#L76)

My guess is that we need to update the code to look like:

```
defaultIfNull(value, defaultValue = '') {
    if (value !== null || value !== undefined) return value;
    return defaultValue;
  }
```

Can you confirm that this fixes your issue?

**Comment by cbaron** [comment]
Unfortunately, we have not implemented `$util.transform.toDynamoDBFilterExpression` -- We should do this.  If you have the time you are welcome to put up a PR.  Let me know if I can assist with that.

**Comment by shwanton** [comment]
Thanks for the quick response. I didn't realize all the `util` functions were re-implemented for the emulator. 

I'm no expert in VTL but it looks like that fix should work for `defaultIfNull`.

This emulator is awesome, especially when you can view changes to a local DynamoDB. Unfortunately, I don't have the bandwidth to implement the missing VTL utils right now.

Thanks again for the help!

**Comment by cbaron** [comment]
Let me know if the fix works.  If so I will put up a PR to include it into master.

**Comment by shwanton** [comment]
Sure thing. I'll make a fork and test it out.
