### ISSUE TITLE
appsync-emulator-serverless: pagination does not work for DynamoDB query/scan resolvers

### ISSUE THREAD

**Issue by asodeur** [ConduitVC/aws-utils#120]
DynamoDB query/scan resolvers always return `nextToken: null`. The issue seems to be that the cursor is not named `NextToken` but `LastEvaluatedKey` in the DynamoDB result.

Additionally AppSync obfuscates the cursor in some way (details are not documented AFAIK).

**Comment by cbaron** [comment]
@asodeur -- thanks for flagging this issue.  Feel free to put up a PR if you have the bandwidth, let me know if I can help you in this regard.

As a team we will look at prioritizing this fix.

**Comment by cbaron** [comment]
@asodeur -- I see you put up a PR!
