### ISSUE TITLE
Failure trying to run tests

### ISSUE THREAD

**Issue by adamclerk** [ConduitVC/aws-utils#123]
I have some suspicions about a bug in the VTL portion of the project.  Specifically the custom value mapper. I'd like to write a few tests to validate my suspicions. But I cannot get the project working according to the readme.  

I'm getting the following:

[![asciicast](https://asciinema.org/a/aNi8YRFeXfk830NWsFUY44Ezb.svg)](https://asciinema.org/a/aNi8YRFeXfk830NWsFUY44Ezb)

Note: I'm also running `npm install` before running `yarn test`. That step is not explicitly called out in the readme. But I assumed it was needed since I'm getting an error from node about missing packages (jest).

**Comment by cbaron** [comment]
Hi @adamclerk!  Good to know another user of the emulator.

We recommend utilizing `yarn` instead of `npm` in this repo.  Try running `yarn` after `rm -rf node_modules` instead of `npm install` -- let me know if that solves your issue.

**Comment by adamclerk** [comment]
That was it. Do you mind if I update the README and issue a PR?

**Comment by cbaron** [comment]
Mind?  I would <3 that!  We encourage contributions!
