### ISSUE TITLE
varibales in tables names in serverless.yml

### ISSUE THREAD

**Issue by SET001** [ConduitVC/aws-utils#17]
It seems like currenlty emulator does not revognize variables in table names in serverless.yml file.

having such a declaration in yml:
`TableName: ens-webhooks-${self:provider.stage}`
I'm getting error this error when starting emulator:

`{ ValidationException: Invalid table/index name.  Table/index names must be between 3 and 255 characters long, and may contain only the characters a-z, A-Z, 0-9, '_', '-', and '.'
`
it's sad that the error message does not contain actual  table name which occures error.

After digging a bit I found that error comes from [asw-sdk](https://github.com/aws/aws-sdk-js/blob/master/lib/sequential_executor.js#L109) and the params passed there contain, among all others, such thing:

`
params:
     { TableName: 'ens-webhooks-${self:provider.stage}',
`

am I doing something wrong or emulator indeed does not support variables in yml?

**Comment by SET001** [comment]
@cbaron I have some free time on this weekends so I difinelty can try to prepare some PR. Can you give me a short help on where to begin with?

**Comment by SET001** [comment]
from what I see in code, here we have [loadServerlessConfig](https://github.com/ConduitVC/aws-utils/blob/master/packages/appsync-emulator-serverless/loadServerlessConfig.js) that can be used to load and parse yml file and seems like it resolves variables correctly. Can it be used in [server.js:createSchema](https://github.com/ConduitVC/aws-utils/blob/cc487ec5a13906da7b351337adcab9517818bd48/packages/appsync-emulator-serverless/server.js#L45)?

**Comment by lightsofapollo** [comment]
@SET001 I added a test case and fixed it for this particular issue. This _should_ be fixed in 0.7.3

**Comment by SET001** [comment]
than you, it is fixed now )

**Comment by SET001** [comment]
I following also related to this issue. The problem is that you can't use `Rel` syntax in yml files. The following defenition
```
    dataSources:
      - type: AMAZON_DYNAMODB
        name: Subscriber
        description: 'Subscribers table'
        config:
          tableName: {Ref: EnsSubscribersDDBTable}
```

result it such an error:

```
✖ error Query.getAllSubscribers failed
✖ error InvalidParameterType: Expected params.TableName to be a string
```

**Comment by lightsofapollo** [comment]
@SET001 This one is harder I don't think we can support cloud formation template syntax at this time. Can you assign the name to a serverless variable and use it in both places?

**Comment by lightsofapollo** [comment]
If needed pleas open a new issue to discuss supporting cloud formation syntax. I don't think we can support it at this time but if it's a serious blocker we can see what we can do.
