### ISSUE TITLE
dynamoDB / direct access

### ISSUE THREAD

**Issue by aheissenberger** [ConduitVC/aws-utils#21]
How can I use the same dynamodb which is created/used by AppSync Emulator to write/read from a normal lambda function called by serverless-offline?

On which local port can I directly access the dynamodb?

Thanks
Andreas
ps. Thanks for creating the AppSync emulator - great work!

**Comment by cbaron** [comment]
Great question.  Will follow up with update to README.

You'll note [here](https://github.com/ConduitVC/aws-utils/blob/92f4bf3ffda9382c30866efbdcc004eba9e93368/packages/appsync-emulator-serverless/lambdaSource.js#L35) that we pass environment variables to the process invoking the lambda method.

So, in your lambda method you can:

```
const dynamodb = new DynamoDB({
  endpoint: process.env.DYNAMODB_ENDPOINT,
  region: 'us-fake-1',
  accessKeyId: 'fake',
  secretAccessKey: 'fake',
});
const client = new DynamoDB.DocumentClient({ service: dynamodb });
const TableName = process.env.DYNAMODB_TABLE_YOURTABLENAME;
```

**Comment by aheissenberger** [comment]
I am not talking about lambda functions which are invoked by the emulator.

I need to access the database from a lambda function which is invoked by `serverless-offline` or `serverless-offline-sns`

Have you thought to add a parameter to use an existing external dynamodb (e.g. serverless-dynamodb-local) or to convert your emulator to a serverless plugin to support a better integration?

**Comment by cbaron** [comment]
>Have you thought to add a parameter to use an existing external dynamodb (e.g. serverless-dynamodb-local) or to convert your emulator to a serverless plugin to support a better integration?

Got it.  We will consider adding this feature in a future iteration.  In the meantime, feel free to put up a PR.
