### ISSUE TITLE
Support custom AWS scalars

### ISSUE THREAD

**Issue by pianomansam** [ConduitVC/aws-utils#25]
I see that AWSJSON support was added recently

https://github.com/ConduitVC/aws-utils/pull/13

It would be great if this supported all custom AWS scalars just like [serverless-appsync-plugin](https://github.com/sid88in/serverless-appsync-plugin/pull/119).

**Comment by cbaron** [comment]
@pianomansam -- thanks for the nudge.  This is something on our list of things to do, and now that you're asking for it, I'll see if we can squeeze in some time to get it landed into master relatively soon.

Good to know of another AppSync developer in Western Michigan 👋 

Also, we of course welcome any pull requests if you're inclined to contribute to the project!

**Comment by pianomansam** [comment]
Here's my pull request that uses `graphql-iso-date` for date related scalars and `@okgrow/graphql-scalars` for email, phone, and URL scalars. I didn't find an easy way to support AWSIPAddress and my project doesn't require it, so I've punted on it.

#26
