### ISSUE TITLE
Handle no appsync resources config

### ISSUE THREAD

**Issue by dingosky** [ConduitVC/aws-utils#29]
The serverless appsync framework does not require a resources section in the config file.

I have a project that is Lambda only and does not access any DynamoDB tables, meaning I do not need (or have) a resources section in my serverless.yml file. The project deploys to AWS AppSync with no issues. I cannot, however, use the appsync emulator since the missing resources config faults.

**Comment by amalow** [comment]
I've forked this project for this exact reason, currently working on a project that only uses Lambda Resolvers so I've nulled out the DynamoDB code; certainly not the right way to do it but it works. Perhaps some configuration changes to only start/use dynamodb if related/required options are specified?

**Comment by dingosky** [comment]
I've submitted a pull request that fixes this issue.

**Comment by cbaron** [comment]
@amalow , @dingosky -- just merged PR, going to close.
