### ISSUE TITLE
Unpublished for 2months

### ISSUE THREAD

**Issue by builtbyproxy** [ConduitVC/aws-utils#36]
Hello

I have seen some pretty critical PR's be approved recently yet the npm package hasn't been published for 2months: https://www.npmjs.com/package/@conduitvc/aws-utils

Is there any update on why this is the case and when it will be republished next?

Thankyou!

**Comment by cbaron** [comment]
@builtbyproxy -- thanks for the reminder!  I published yesterday!

**Comment by builtbyproxy** [comment]
Awesome thanks!
