### ISSUE TITLE
Serverless Appsync Offline quits on Serverless 1.33

### ISSUE THREAD

**Issue by pianomansam** [ConduitVC/aws-utils#46]
This is a cross post from the [main issue](https://github.com/aheissenberger/serverless-appsync-offline/issues/8) I submitted on Serverless Appsync Offline.

When running `serverless appsync-offline start`, ever since upgrading to Serverless 1.33, the command quits as soon as the GraphQL server comes up. From my logs, when using nodemon:

```
ℹ️  appsync-emulator:serverCore server bound { address: '::', family: 'IPv6', port: 62222 }
Serverless: AppSync started: http://localhost:62222/graphql
[nodemon] clean exit - waiting for changes before restart
```

You'll notice that while it exits cleanly, it doesn't do any of the cleanup. Otherwise we would see a line like `AppSync offline - stopping graphql and dynamoDB`.

I'm not sure if the bug is in this library or Serverless Appsync Offline.

**Comment by EwanValentine** [comment]
I've ran into this on version 1.36.0 of Serverless.

**Comment by pianomansam** [comment]
Yeah, I have my Serverless version pinned to `1.32`

```
"serverless": "1.32.0"
```

**Comment by pianomansam** [comment]
For what it's worth, I'm not having issues with serverless `1.38.0`

**Comment by cbaron** [comment]
@pianomansam -- going to close this issue, please reopen if you see fit
