### ISSUE TITLE
Call lambda code using python runtime 

### ISSUE THREAD

**Issue by danifbento** [ConduitVC/aws-utils#50]
Hello,

I'm trying to configure appsync-serverless-emulator to run AppSync and to call some local lambdas.

At this moment the serverless is configured to use python3.6 runtime for the function that I'm trying to call. But, for instance, when I call my Query on GraphQL which should call the respective Lambda, debugging the appsync-emulator-serverless shows that is trying to call a NodeJS version of it. How can I configure the emulator to run also Python code? Or this implementation doesn't work in that way?

And it is possible to call deployed lambdas with the appsync-serverless-emulator offline?

Thanks,

**Comment by cbaron** [comment]
Currently, the emulator only supports calling nodejs lambda methods.  However, it will not be difficult to implement a python implementation of lambda.

Could I interest you in putting up a PR to implement a python solution?  I will gladly assist on the way.

Currently, the node implementation is here: https://github.com/ConduitVC/aws-utils/blob/master/packages/appsync-emulator-serverless/lambdaRunner.js

[Here](https://github.com/ConduitVC/aws-utils/blob/71ae2f3774540b425b70fb56a2836bf0b963f75d/packages/appsync-emulator-serverless/lambdaSource.js#L41) is where the lambda method is called.

**Comment by danifbento** [comment]
Hey,

Thanks for the fast reply. I will try to do PR with a Python solution :)

I will look for the references.

**Comment by danifbento** [comment]
I add a WIP here:
https://github.com/ConduitVC/aws-utils/pull/56

can you check?

**Comment by danifbento** [comment]
Can I close this issue?
