### ISSUE TITLE
Merge graphql-phone-type into aws-utils

### ISSUE THREAD

**Issue by marklawlor** [ConduitVC/aws-utils#73]
`appsync-emulator-serverless` depends on https://github.com/pianomansam/graphql-phone-type which is to minor fork of https://github.com/enniel/graphql-phone-type

Instead of relying on the fork, it may be useful to roll that package into this monorepo and publish it under the @conduitvc scope. Either that or push the changes back upstream to the original package

@pianomansam 

There are some minor updates I'd like to perform on the package, such as renaming its `prepare` script to something else [as it is causing intermittent issues within my CI environment](https://github.com/yarnpkg/yarn/issues/6312#issuecomment-422806004). But I'd prefer for this repo formalise which package it is using before I do the PR.

**Comment by pianomansam** [comment]
I have no problem with this. Utilizing `enniel/graphql-phone-type` was just an attempt to not reinvent the wheel. Placing our fork within this monorepo is okay with me. I'm just not a maintainer :)

**Comment by cbaron** [comment]
@marklawlor -- I have seen intermittent issues within my CI environment as well.  Feel free to submit a PR to add it to this monorepo.
