### ISSUE TITLE
Can't get specs running on Mac

### ISSUE THREAD

**Issue by mattgibson** [ConduitVC/aws-utils#78]
I'm trying to get the project set up to start some work on adding a new feature, but the README's instructions of just using `yarn jest` after `docker-compose up` leads to quite a few failures.

`travis.yml` seems to show a more complicated setup, but I've as yet not been able to get the specs to all pass even after running the commands in that file. Errors seem to be around python and go lambda code mostly.

Could a section be added to the README showing how to get all the specs to run locally after a clean checkout please? I'm on MacOS 10.14.3.

**Comment by cbaron** [comment]
Hi @mattgibson -- my apologies for the lack of documentation, but aws-utils contains a series of packages for individual use cases.  Is there a particular package you're looking to utilize?

You can start by running `yarn` in the root directly to install all packages and their dependencies within the repo.

I hope you're using the appsync emulator serverless package, if so you can find more info [here](https://github.com/ConduitVC/aws-utils/tree/master/packages/appsync-emulator-serverless)

We would greatly appreciate it if you wanted to help us with documentation by improving the README as you have the best perspective as someone who is using the repo for the first time.

**Comment by mattgibson** [comment]
Hi @cbaron 

I'm working right now on using the appsync emulator serverless package to run Ruby code, which is not currently supported. I want to add that feature.

I've got the specs running now, although it's taken days to do it. I'm happy to improve the docs, so I'll make a PR for the README with all the things I've learned.

**Comment by cbaron** [comment]
Awesome!

**Comment by mattgibson** [comment]
This improves things a bit, I think https://github.com/ConduitVC/aws-utils/pull/80
