### ISSUE TITLE
make Dynamodb optional?

### ISSUE THREAD

**Issue by bboure** [ConduitVC/aws-utils#82]
Hi all,

For what I can understand from doc and code, dynamodb seems to be required, whether it's dynamodb local or a custom dynamodb server.
I am not using dynamodb at all in my project (neither with resolvers, nor from lambda). I just use Lambda and a neo4j DB.
I was looking for a way to skip any dynamodb from starting with the emulator but I don't think it's possible.
Did I miss something?

I am using this package in association with https://github.com/aheissenberger/serverless-appsync-offline

Did I miss something? is this something possible?
And should we consider making it optional? 
I would be open to make a PR for that.

**Comment by cbaron** [comment]
@bboure -- I believe we do assume that .vtl templates and a dynamodb datastore will always be used.  I think it would be great if we made DynamoDB optional for cases such as yours 👍

**Comment by lightsofapollo** [comment]
Great point... AppSync is less and less dynamodb centric over time.
