### ISSUE TITLE
Converting circular structure to JSON on $utils.toJson($context) at ....

### ISSUE THREAD

**Issue by bboure** [ConduitVC/aws-utils#96]
Since this commit: acad4497600e071eae56765a2dcfa671315c66a5
I am getting this error when doing
`$utils.toJson($context)`.

This happens I believe because there must have some circular reference in the request object https://github.com/ConduitVC/aws-utils/blob/master/packages/appsync-emulator-serverless/serverCore.js#L280

@JimmyHurrah

**Comment by cbaron** [comment]
@bboure -- thinking we should explicitly define the attributes we pass along to the VTL context.  Did you have any other ideas?

**Comment by cbaron** [comment]
Going to put up a PR.
